In [ ]:
#importing
import numpy as np

In [ ]:
!pip install np

  Preparing metadata (setup.py) ... done
  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13658 sha256=9422158a7077c26c58d52218b1c8e22c3fdbbf653b7d4b5c9cf8f94957fc7fec
  Stored in directory: /root/.cache/pip/wheels/f9/e1/79/c4580a03022dece233bc146286fc9082a8885ee1a7c8d8b980
Successfully built np


Arrays

In [ ]:
#creating 1D array
A=np.array([2,2,7,9])
print(type(A))

<class 'numpy.ndarray'>


In [ ]:
#CREATING A 2D ARRAY
B=np.array([[1,2,3],[4,5,6]])
print(B)

[[1 2 3]
 [4 5 6]]


In [ ]:
#creating a 3d array-rows,columns,groups
C=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(C)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [ ]:
#CHECKING DIMENSIONS
print(A.ndim)
print(B.ndim)
print(C.ndim)

1
2
3


In [ ]:
D=np.ones((3,2))
print(D)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
D=np.ones((2,3,2))
print(D)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
#ONES
E=np.ones((3,2))#rows,colums,2D
print(E)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#zeros
F=np.zeros((3,2))#2D
print(F)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
J=np.eye(4)
print(J)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#arange
H=np.arange(2,30,2)#start,stop,step
print(H)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [ ]:
H=np.arange(2,30,2).reshape(7,2)
print(H)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]
 [22 24]
 [26 28]]


In [ ]:
H=np.arange(5,1001,5)
print(H)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

In [ ]:
#linespace
V=np.linspace(10,20,10)
print(V)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [ ]:
L=np.arange(2,8).reshape(2,3)
print(L)
H=np.arange(4,10).reshape(2,3)
print(H)

[[2 3 4]
 [5 6 7]]
[[4 5 6]
 [7 8 9]]


In [ ]:
print(L+H)

[[ 6  8 10]
 [12 14 16]]


In [ ]:
n=np.sum(H+L)
print(n)

66


In [ ]:
G=np.sum((H,L),axis=0)
print(G)

[[ 6  8 10]
 [12 14 16]]


In [ ]:
G=np.sum((H,L),axis=1)
print(G)

[[11 13 15]
 [ 7  9 11]]


In [ ]:
n=np.ones((4,2))
h=np.ones((4,2))
print(np.sum((n,h),axis=0))
print(np.sum((n,h),axis=1))

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]
[[4. 4.]
 [4. 4.]]


In [ ]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,2]])
print(A*B)
print(A@B)

[[2 0]
 [0 2]]
[[5 2]
 [3 2]]


b=np.array[25,289,361,81]#find square roots and iterate through result values output:5 square is 25..

In [ ]:
b=np.array([25,289,361,81])
for i in b:
  print((np.sqrt(i)),"square is",i)


5.0 square is 25
17.0 square is 289
19.0 square is 361
9.0 square is 81


Array joins

In [ ]:
a=np.array([1,2,3,4,5,6])
a.resize(2,3)
print(a)
b=np.array([10,11,12,13,14,15])
b.resize(2,3)
print(b)
print(np.vstack((a,b)))#coloumns
print("\n")
print(np.hstack((a,b)))#rows

[[1 2 3]
 [4 5 6]]
[[10 11 12]
 [13 14 15]]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [13 14 15]]


[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("\n")
print(np.dstack(a))#groups becomes coloumns,number of rows becomes number of groups,coloumns becomes rows

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]
