In [ ]:
#importing
import numpy as np
#RANDOM MODULE IS SUB-PACKAGE OF NUMPY



In [ ]:
!pip install np

  Preparing metadata (setup.py) ... done
  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13658 sha256=8488e41545c44741ed1fe1a1731ec31f2be83df8b3a7264a985a757c0df014f9
  Stored in directory: /root/.cache/pip/wheels/f9/e1/79/c4580a03022dece233bc146286fc9082a8885ee1a7c8d8b980
Successfully built np


In [ ]:
a=np.ones((8,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
b=np.arange(1,33,1).reshape(8,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
H=np.random.rand(1)
print(H)

[0.53281024]


In [ ]:
A=np.random.rand(8,4)#rand range is between 0 to 1
print(A)

[[0.01633655 0.71324665 0.93775797 0.53335008]
 [0.090491   0.03616235 0.32751192 0.85206397]
 [0.75616349 0.53746053 0.08975027 0.81600267]
 [0.17561724 0.16506891 0.41041712 0.653869  ]
 [0.3557942  0.25469196 0.78588892 0.88262353]
 [0.95583901 0.68431961 0.37648377 0.92097869]
 [0.43827062 0.36740763 0.4411294  0.57316322]
 [0.36463893 0.3453167  0.01030147 0.93866492]]


In [ ]:
A=10*np.random.rand(8,4)
print(A)

[[5.43217913 8.3082186  6.70887995 9.94862296]
 [4.02695758 2.37033594 4.45154198 4.28700573]
 [6.14832352 8.55903302 2.38126096 3.95196743]
 [3.93392599 7.47269208 0.83550519 0.18182248]
 [3.10357608 2.84935526 8.57071682 0.73685941]
 [2.84945613 1.43150154 8.10248042 2.79148042]
 [7.74086394 8.27457078 2.17837058 7.62595935]
 [4.32736875 9.7802598  8.86954916 4.44764323]]


In [ ]:
A=np.floor(10*np.random.rand(8,4))
print(A)

[[6. 8. 0. 3.]
 [3. 2. 7. 3.]
 [7. 1. 2. 6.]
 [2. 8. 6. 9.]
 [3. 2. 2. 3.]
 [0. 4. 6. 3.]
 [8. 2. 7. 7.]
 [3. 4. 1. 6.]]


In [ ]:
np.vsplit(A,4)

[array([[6., 8., 0., 3.],
        [3., 2., 7., 3.]]),
 array([[7., 1., 2., 6.],
        [2., 8., 6., 9.]]),
 array([[3., 2., 2., 3.],
        [0., 4., 6., 3.]]),
 array([[8., 2., 7., 7.],
        [3., 4., 1., 6.]])]

In [ ]:
np.vsplit(A,(3,5))#split it after 3rd row and 5th row

[array([[6., 8., 0., 3.],
        [3., 2., 7., 3.],
        [7., 1., 2., 6.]]),
 array([[2., 8., 6., 9.],
        [3., 2., 2., 3.]]),
 array([[0., 4., 6., 3.],
        [8., 2., 7., 7.],
        [3., 4., 1., 6.]])]

In [ ]:
np.hsplit(A,(1,4))

[array([[6.],
        [3.],
        [7.],
        [2.],
        [3.],
        [0.],
        [8.],
        [3.]]),
 array([[8., 0., 3.],
        [2., 7., 3.],
        [1., 2., 6.],
        [8., 6., 9.],
        [2., 2., 3.],
        [4., 6., 3.],
        [2., 7., 7.],
        [4., 1., 6.]]),
 array([], shape=(8, 0), dtype=float64)]

In [ ]:
B=np.arange(1,33,1).reshape(4,8)
print(B)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(B,4)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(B,(4,7))#split it after 4th column and 7th column

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28]]),
 array([[ 5,  6,  7],
        [13, 14, 15],
        [21, 22, 23],
        [29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

In [ ]:
np.pi

3.141592653589793

In [ ]:
n=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(n)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(n)

array([ 45.,  60.,  90., 180.])

In [ ]:
b=([ 45.,  60.,  90., 180.])
np.deg2rad(b)

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(90)#radians

0.8939966636005579

In [ ]:
np.tan(45)

1.6197751905438615

In [ ]:
np.cos(1)

0.5403023058681398

Statistics

In [ ]:
st=np.array([11,22,33,44,55])

In [ ]:
np.mean(st)

33.0

In [ ]:
np.median(st)

33.0

In [ ]:
np.std(st)

15.556349186104045

In [ ]:
np.var(st)

242.0

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(C)#linear algebra is sub-package of numpy

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
x=np.random.rand(1,25).reshape(1,25)
print(np.argmax(x))
print(x)

19
[[0.83907901 0.48899188 0.5229184  0.09358676 0.86279143 0.29080021
  0.69265934 0.56977571 0.88644153 0.39311617 0.35418869 0.98035403
  0.7153259  0.32758173 0.47889927 0.60171202 0.00808901 0.82517133
  0.18949706 0.98744354 0.54577258 0.41712265 0.67117955 0.38876093
  0.08101763]]


In [ ]:
print(np.argmax(x))

19


In [ ]:
C=np.arange(1,33,1).reshape(8,4)
print(C)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
print(np.argmax(C,axis=1))
print(np.argmax(C,axis=0))

[3 3 3 3 3 3 3 3]
[7 7 7 7]


In [ ]:
print(np.argmin(C))

0


In [ ]:
print(np.argmin(C,axis=1))
print(np.argmin(C,axis=0))

[0 0 0 0 0 0 0 0]
[0 0 0 0]


Searching

In [ ]:
H=np.array([11,45,22,79,14,8])
print(np.where(H%2==0))

(array([2, 4, 5]),)


In [ ]:
print(np.where(H%2==1))

(array([0, 1, 3]),)


In [ ]:
a=np.array([24,16,7,17,54,60])
print(np.where(a%6==0))

(array([0, 4, 5]),)


In [ ]:
z=np.array([4,7,8,9,10])
x=np.searchsorted(z,8)#gives the index position of element to be searched
print(x)

2


In [ ]:
y=np.searchsorted(H,8)
print(y)

0


In [ ]:
ar=np.array([1,10,9,6,7,4])
print(np.sort(ar))
c=np.searchsorted(ar,4)
print(c)


[ 1  4  6  7  9 10]
1


In [ ]:
arr=np.array([ True,False,True])
print(np.sort(arr))

[False  True  True]


In [ ]:
X=np.array([[3,2,4],[5,1,0]])#sorting happens within row
print(np.sort(X))

[[2 3 4]
 [0 1 5]]


array filter

In [ ]:
arr=np.array([49,50,47,24,78,14])
filt=np.where(arr%2==0) #filters can work for both arrays and lists
print(filt)

(array([1, 3, 4, 5]),)


In [ ]:
arr[filt]

array([50, 24, 78, 14])

Iterating through two arrays

In [ ]:
names=np.array(["hema","neha","vyshu","divya","gopi"])
initials=np.array(["V","M","Y","K","A"])
for i,j in zip(initials,names):
  print(i,".",j)

V . hema
M . neha
Y . vyshu
K . divya
A . gopi


In [ ]:
n1=np.array([10,20,30,40,50])
n2=np.array([60,70,80,90,10])
a=np.multiply(n1,n2)
print(a)

[ 600 1400 2400 3600  500]


In [ ]:
n1=np.array([10,21,30,40,50,60])
n2=np.array([20,21,2,20,25,25])
b=np.divide(n1,n2)
print(b)

[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
n1=np.array([10,21,30,40,50,60])
n2=np.array([20,21,2,20,25,25])
b=np.mod(n1,n2)
print(b)

[10  0  0  0  0 10]


In [ ]:
n1=np.array([10,21,30,40,50,60])
n2=np.array([20,21,2,20,25,25])
b=np.divmod(n1,n2)
print(b)

(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


Logarithms

In [ ]:
a1=np.arange(2,8)#base 2
print(a1)
print(np.log2(a1))

[2 3 4 5 6 7]
[1.         1.5849625  2.         2.32192809 2.5849625  2.80735492]


In [ ]:
a1=np.arange(2,8)#base 10
print(a1)
print(np.log10(a1))

[2 3 4 5 6 7]
[0.30103    0.47712125 0.60205999 0.69897    0.77815125 0.84509804]


In [ ]:
a1=np.arange(2,8)#natural logarithm-base e
print(a1)
print(np.log(a1))

[2 3 4 5 6 7]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015]


In [ ]:
num1=np.array([24,26,45,74])
x=np.cumprod(num1)
print(x)

[     24     624   28080 2077920]


In [ ]:
num1=np.array([24,26,45,74])
x=np.cumsum(num1)
print(x)

[ 24  50  95 169]


In [ ]:
a=np.array([2,4,6,8,10])
newar=np.diff(a)
print(newar)

[2 2 2 2]


In [ ]:
num1=455
num2=665
x=np.lcm(num1,num2)
print(x)

8645


In [ ]:
num1=455
num2=665
x=np.gcd(num1,num2)
print(x)

35


In [ ]:
a=np.array([12,15,18,60])
gc=np.gcd.reduce(a)#takes multiple inputs and gives single output
print(gc)

3


In [ ]:
a=np.array([12,15,18,60])
gc=np.lcm.reduce(a)#takes multiple inputs and gives single output
print(gc)

180
